### ISSUE TITLE
assimp4java module cannot build

### ISSUE THREAD

**Issue by Sailsman63** [xbuf/assimp_xbuf#1]
Has anyone managed to build the assimp4java module recently? The gradle build fusses about lack of a developer key (It seems to be trying to deploy directly to bitbucket?) and I have not been able to get javacpp to complete. (Native compilation step (g++) seems to be having issues with header include order)
The reason that I ask is I want to use this module as a stand-alone, without any of the rest of the xbuf stuff. I hope to eventually extend it to include mapping for the export functionality.

**Comment by davidB** [comment]
I updated and fixed the build of assimp4java (but not for assulo2xbuf that you don't care).
```
cd assimp4java
../gradlew clean assemble
```

**Comment by Sailsman63** [comment]
Thanks for the quick reply and fix. I did manage (very late after posting) to get compilation to work from the command line, but the gradle version is soo much simpler to use.
